name: DevHub Frontend CICD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Frontend Build - nodeJS v${{ matrix.node-version }}
        run: .github/workflows/frontend.sh
        env:
          DEVHUB_BACKEND_API: ${{ secrets.DEVHUB_BACKEND_API }}

      - uses: actions/upload-artifact@v3
        with:
          name: dist-node-${{ matrix.node-version }}
          path: frontend/dist.tar.gz
